// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpkqwtbvvaklwclnlgjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwa3F3dGJ2dmFrbHdjbG5sZ2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2Mzk4NDAsImV4cCI6MjA1MzIxNTg0MH0.9hUUBE0KUiDgRltst-IThrGB0r_p3AScAqXJWAA32QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);